name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODE: production      
    steps:
      # Setup the enviroment
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Set up Node.js
      uses: actions/setup-node@v1

      # Setup the build
    - name: Initialize
      run: npm i

      # Build
    - name: Build
      run: |
        ./build.sh
        cp webserver/index.html resources/index.html
      
      # Upload
    - name: Upload Resources
      uses: actions/upload-artifact@v2.2.4
      with:
        name: spaghetti.js+resources
        path: resources
    - name: Upload Spaghetti
      uses: actions/upload-artifact@v2.2.4
      with:
        name: spaghetti.js
        path: resources/bin/spaghetti.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: spaghetti.js+resources
          path: tmp

      - name: Prepare folders
        run: |
          mkdir resources
          cp tmp/bin resources/bin
          cp tmp/index.html ./index.html
          rm -rf tmp

      - name: Publish Pages
        uses: peaceiris/actions-gh-pages@v3        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
