name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    env:
      MODE: production
      
    steps:
    # Setup the enviroment
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Set up Node.js
      uses: actions/setup-node@v1

    # Setup the build
    - name: Initialize
      run: npm i

    # Build
    - name: Build
      run: ./build.sh
      
    # Upload
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: resources/bin/spaghetti.js
    
